FROM java:8
MAINTAINER javaonfly
COPY /ServiceRegistration/target/ServiceRegistration-0.0.1-SNAPSHOT.jar ServiceRegistration-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "ServiceRegistration-0.0.1-SNAPSHOT.jar"]
EXPOSE 8761